#if !defined(_THRESHOLD_)
#define _THRESHOLD_

#define UCS_d_AngleRadZero 0.001
#define UCS_d_AngleGradZero  0.01
#define UCS_d_GeometricZero  0.01

	     
#define UCS_i_BasePointMarkerSizeX  10
#define UCS_i_BasePointMarkerSizeY  10

#define UCS_i_SolidAxis  2

#define UCS_i_AxisSizeX 50
#define UCS_i_AxisSizeY 50
#define UCS_i_AxisSizeZ 50
	  

#define MDI_i_BkColorIndexInSYSPalette  6
#define MDI_i_AxisBackColorIndexInSYSPalette 12
#define MDI_i_AxisFaceColorRGBr  0xFF
#define MDI_i_AxisFaceColorRGBg  0xFF
#define MDI_i_AxisFaceColorRGBb  0xFF

	  
#define MDI_i_GridColorRGBr 0xFF
#define MDI_i_GridColorRGBg 0xFF
#define MDI_i_GridColorRGBb 0xFF


#define MDI_d_AutoScrollH 0.2
#define MDI_d_AutoScrollV 0.2
#define MDI_d_AutoScrollFeedH 15
#define MDI_d_AutoScrollFeedV 15
     

#define  MDI_d_DrawArrowMinDistance  0.001
#define  MDI_i_DrawArrowLenght 15

#define  MDI_d_GradusStepOnRotate  5.0

#define  MDI_i_SelectFacetGeometricMouseStep 10

#define  MDI_d_VPortAligmentNormZero 0.001

#define  MDI_d_MinScaleAbs 0.01
#define  MDI_d_MoveSpeedCorrect 1.5
#define	 MDI_d_ScaleSpeedCorrect 0.7
#define	 MDI_d_Scale2DSpeedCorrect 0.7
#define	 MDI_d_RotateSpeedCorrect 0.7


#define MDI_d_MinRadiusConeCylind 1.0
#define	MDI_d_MinRadiusSphere 1.0
#define	MDI_d_MinHighBody 1.0
#define	MDI_d_MinRadiusTorus1 1.0
#define	MDI_d_MinRadiusTorus2 2.0
#define MDI_d_MinRadiusTube1 1.0
#define	MDI_d_MinRadiusTube2 2.0

#define	MDI_d_MinDeltaWindowH 5.0
#define	MDI_d_MinDeltaWindowV 5.0


#define SCENA_d_ZoomToFitBorderX  0.15
#define	SCENA_d_ZoomToFitBorderY  0.15

#define SCENA_i_SelectObjectDelta 10

#define SCENA_d_VectorZAbsOutNormalVisible 0.005
#define	SCENA_d_AligmentZNormalZero 0.001

#define	TRACER_d_ZOutNormalVisibleReal  0.02
#define	TRACER_d_ZOutNormalVisibleInt  0.05
#define	TRACER_d_ZOutNormalVisibleStrScan -0.05

#define	TRACER_d_TransparencyZero 0.01

#define	TRACER_i_AntialiasingNumbCells  4

#define	TRACER_d_ShadingSclrZero  0.01

#define	TFACET_d_HorizontalAdge 0.01

#endif
