#if !defined(_BPDLG_BITMAP_INC_)
#define _BPDLG_BITMAP_INC_

#define BPDLG_NUMB_CONTROL_BMP  4
#define BPDLG_NUMB_CHECK_BMP    9


#define BPDLG_FIRSTID_N         350
#define BPDLG_FIRSTID_H         400
#define BPDLG_FIRSTID_S         450


#define BPDLGBMP_POINT_N                (BPDLG_FIRSTID_N + 1)
#define BPDLGBMP_POINT_H                (BPDLG_FIRSTID_H + 1)
#define BPDLGBMP_POINT_S                (BPDLG_FIRSTID_S + 1)

#define BPDLGBMP_VERTEX_N               (BPDLG_FIRSTID_N + 2)
#define BPDLGBMP_VERTEX_H               (BPDLG_FIRSTID_H + 2)
#define BPDLGBMP_VERTEX_S               (BPDLG_FIRSTID_S + 2)

#define BPDLGBMP_BODY_N                 (BPDLG_FIRSTID_N + 3)
#define BPDLGBMP_BODY_H                 (BPDLG_FIRSTID_H + 3)
#define BPDLGBMP_BODY_S                 (BPDLG_FIRSTID_S + 3)

#define BPDLGBMP_CANCEL_N               (BPDLG_FIRSTID_N + 4)
#define BPDLGBMP_CANCEL_H               (BPDLG_FIRSTID_H + 4)
#define BPDLGBMP_CANCEL_S               (BPDLG_FIRSTID_S + 4)



#define BPDLGBMP_TOPLEFT_N              (BPDLG_FIRSTID_N + 5)
#define BPDLGBMP_TOPLEFT_H              (BPDLG_FIRSTID_H + 5)
#define BPDLGBMP_TOPLEFT_S              (BPDLG_FIRSTID_S + 5)

#define BPDLGBMP_TOP_N                  (BPDLG_FIRSTID_N + 6)
#define BPDLGBMP_TOP_H                  (BPDLG_FIRSTID_H + 6)
#define BPDLGBMP_TOP_S                  (BPDLG_FIRSTID_S + 6)

#define BPDLGBMP_TOPRIGHT_N             (BPDLG_FIRSTID_N + 7)
#define BPDLGBMP_TOPRIGHT_H             (BPDLG_FIRSTID_H + 7)
#define BPDLGBMP_TOPRIGHT_S             (BPDLG_FIRSTID_S + 7)

#define BPDLGBMP_LEFT_N                 (BPDLG_FIRSTID_N + 8)
#define BPDLGBMP_LEFT_H                 (BPDLG_FIRSTID_H + 8)
#define BPDLGBMP_LEFT_S                 (BPDLG_FIRSTID_S + 8)

#define BPDLGBMP_CENTER_N               (BPDLG_FIRSTID_N + 9)
#define BPDLGBMP_CENTER_H               (BPDLG_FIRSTID_H + 9)
#define BPDLGBMP_CENTER_S               (BPDLG_FIRSTID_S + 9)

#define BPDLGBMP_RIGHT_N                (BPDLG_FIRSTID_N + 10)
#define BPDLGBMP_RIGHT_H                (BPDLG_FIRSTID_H + 10)
#define BPDLGBMP_RIGHT_S                (BPDLG_FIRSTID_S + 10)

#define BPDLGBMP_BOTTOMLEFT_N           (BPDLG_FIRSTID_N + 11)
#define BPDLGBMP_BOTTOMLEFT_H           (BPDLG_FIRSTID_H + 11)
#define BPDLGBMP_BOTTOMLEFT_S           (BPDLG_FIRSTID_S + 11)

#define BPDLGBMP_BOTTOM_N               (BPDLG_FIRSTID_N + 12)
#define BPDLGBMP_BOTTOM_H               (BPDLG_FIRSTID_H + 12)
#define BPDLGBMP_BOTTOM_S               (BPDLG_FIRSTID_S + 12)

#define BPDLGBMP_BOTTOMRIGHT_N          (BPDLG_FIRSTID_N + 13)
#define BPDLGBMP_BOTTOMRIGHT_H          (BPDLG_FIRSTID_H + 13)
#define BPDLGBMP_BOTTOMRIGHT_S          (BPDLG_FIRSTID_S + 13)


#endif

