#if !defined(_DIALOG_INC_)
#define _DIALOG_INC_

#define  DL_DUPSTART   300
#define  BL_SWT        101
#define  BL_UNDOSTART  102

#define  DlgFileOpen   50
#define  DlgFileSave   51
#define  ID_FTYPE      52

#define  DlgYNC        53

#define  DlgViewsDiv   54
#define  ID_VIEWBTN_FIRST 119
#define  ID_TOP        120
#define  ID_BOTTOM     121
#define  ID_USER       122
#define  ID_LEFT       123
#define  ID_RIGHT      124
#define  ID_CAMERA     125
#define  ID_FRONT      126
#define  ID_BACK       127
#define  ID_NONE       128
#define  ID_VIEWBTN_END 129

#define  ID_CHECK_DEF    130
#define  ID_CHECK_INIT   131
#define  ID_CHECK_GRP    132

#define  ID_DIVBTN_FIRST 133
#define  ID_DIVBTN_END   148

#define  DlgGridExtents  149
#define  ID_STA_X        150
#define  ID_END_X        151
#define  ID_STA_Y        152
#define  ID_END_Y        153
#define  ID_SPACE_X      154
#define  ID_SPACE_Y      155

#define  DlgCreateBody   156
#define  ID_CHECK_SMOTH  157
#define  ID_VALUE_TB1    158
#define  ID_VALUE_TB2    159
#define  ID_LIST         160
#define  ID_SELECT_BMP   161

#define  DlgSceneInfo    162
#define  ID_LIST_TXT     163

#define  DlgSaveBmp      164

#define  DlgProgressInd  165

#define  ID_TEXTSPACE    166

#define  DlgMedSave      167
#define  DlgMedLoad      168

#define  ID_CHECK_ALIGN  169

#define  DlgAligment     170
#define  DlgAmbient      171
#define  DlgPolyhonalRender 172
#define  DlgBkGnd        173
#define  DlgImageOpt     174
#define  DlgOmniAdjust   175
#define  DlgPlaceHilite  176
#define  DlgPhoto        177
#define  DlgSmoth        178
#define  DlgNoisy        179

#endif
