#if !defined(_IMAGESETUP_DLG_INC_)
#define _IMAGESETUP_DLG_INC_

#define ID_IMG_STA                 101

#define ID_ISDLG_256_RADIO         101
#define ID_ISDLG_236_RADIO         102
#define ID_ISDLG_16SYS_RADIO       103
#define ID_ISDLG_16ADAPT_RADIO     104
#define ID_ISDLG_TRUECOLOR_RADIO   105

#define ID_ISDLG_WINDOWED_RADIO    106
#define ID_ISDLG_FULLSCREEN_RADIO  107
#define ID_ISDLG_640x480_RADIO     108
#define ID_ISDLG_800x600_RADIO     109
#define ID_ISDLG_1024x768_RADIO    110

#define ID_IMG_END                 110

#define ID_METHOD_STA              111

#define  ID_RADIO_QUANT            111
#define  ID_RADIO_MEDIUMSECT       112
#define  ID_RADIO_GEOMETRIC        113
#define  ID_RADIO_DISCRET          114
#define  ID_CHECK_DIFFUSION        115
#define  ID_CHECK_NOISY            116

#define ID_METHOD_END              116

#define  ID_GRP_METHODS            120
#define  ID_GRP_PALETTE            121
#define  ID_GRP_FORMAT             122


#endif
