#if !defined(_MEDDLG_BMP_INC_)
#define _MEDDLG_BMP_INC_

#define MEDDLG_NUMB_CONTROL_BMP  2


#define MEDDLG_FIRST_N         550
#define MEDDLG_FIRST_H         555
#define MEDDLG_FIRST_S         560



#define  MEDDLG_ADD_N              (MEDDLG_FIRST_N + 1)
#define  MEDDLG_ADD_H              (MEDDLG_FIRST_H + 1)
#define  MEDDLG_ADD_S              (MEDDLG_FIRST_S + 1)

#define  MEDDLG_DELETE_N           (MEDDLG_FIRST_N + 2)
#define  MEDDLG_DELETE_H           (MEDDLG_FIRST_H + 2)
#define  MEDDLG_DELETE_S           (MEDDLG_FIRST_S + 2)


#endif
