#if !defined(_NOISY_DLG_INC_)
#define _NOISY_DLG_INC_

#define IDNOISY_RADIO_MARGINAL           101
#define IDNOISY_RADIO_UNIFORM            102
#define IDNOISY_RADIO_NONE               103

#define IDNOISY_INPUT_MARGINAL_AMPL      104
#define IDNOISY_INPUT_UNIFORM_AMPL       105
#define IDNOISY_INPUT_UNIFORM_THSRESOL   106
					 
#define IDNOISY_SCROLL_UNIFORM_THSRESOL  107

#define IDNOISY_GRP_MAIN                 108

#endif


