#if !defined(_OMNI_INC_)
#define _OMNI_INC_

#define ID_OMNIDLG_RGB_R_INPUT      101
#define ID_OMNIDLG_RGB_G_INPUT      102
#define ID_OMNIDLG_RGB_B_INPUT      103
#define ID_OMNIDLG_RGB_R_SCROLL     104
#define ID_OMNIDLG_RGB_G_SCROLL     105
#define ID_OMNIDLG_RGB_B_SCROLL     106
#define ID_OMNIDLG_RGB_MIX          107

#define ID_OMNIDLG_MULT_INPUT       108

#define ID_OMNIDLG_ON_RADIO         109
#define ID_OMNIDLG_OFF_RADIO        110
#define ID_OMNIDLG_SHADOWS_CHECK    111
#define ID_OMNIDLG_OPT_GRP          112

#endif
