#if !defined(_PHOTO_INC_)
#define _PHOTO_INC_

#define  ID_PHDLG_GRP_OPTIONS          101
#define  ID_PHDLG_GRP_SHADINGLIM       102
#define  ID_PHDLG_GRP_RENDERALHORITM   103
#define  ID_PHDLG_GRP_TRACEMETHOD      104

#define  ID_PHDLG_CHECK_ANTIALIASING   105
#define  ID_PHDLG_CHECK_SHADOWS        106

#define  ID_PHDLG_INPUT_NUMBPIXELS     108
#define  ID_PHDLG_INPUT_STRENGTS       120

#define  ID_PHDLG_RADIO_FLAT           109
#define  ID_PHDLG_RADIO_PHONG          110

#define  ID_PHDLG_RADIO_RAY            111
#define  ID_PHDLG_RADIO_STRING         112

#define  ID_PHDLG_RADIO_LOCAL          113
#define  ID_PHDLG_RADIO_GLOBALHOLLS    114

#define  ID_CHECK_STRICTGAMMA          130


#endif

