#if !defined(_VIEWS_BMP_INC_)
#define _VIEWS_BMP_INC_

#include "F:\WORK_C\3DW\INC\windiv.typ"

#define VBMP_FIRST_N 100
#define VBMP_FIRST_H 150


#define VBMP_N_DS_FullWin               (VBMP_FIRST_N + DS_FullWin)
#define VBMP_H_DS_FullWin               (VBMP_FIRST_H + DS_FullWin)

#define VBMP_N_DS_HalfVert              (VBMP_FIRST_N + DS_HalfVert)
#define VBMP_H_DS_HalfVert              (VBMP_FIRST_H + DS_HalfVert)

#define VBMP_N_DS_HalfHor               (VBMP_FIRST_N + DS_HalfHor)
#define VBMP_H_DS_HalfHor               (VBMP_FIRST_H + DS_HalfHor)

#define VBMP_N_DS_4                     (VBMP_FIRST_N + DS_4)
#define VBMP_H_DS_4                     (VBMP_FIRST_H + DS_4)

#define VBMP_N_DS_HalfVertAndLeftHor    (VBMP_FIRST_N + DS_HalfVertAndLeftHor)
#define VBMP_H_DS_HalfVertAndLeftHor    (VBMP_FIRST_H + DS_HalfVertAndLeftHor)

#define VBMP_N_DS_HalfHorAndDownVert    (VBMP_FIRST_N + DS_HalfHorAndDownVert)
#define VBMP_H_DS_HalfHorAndDownVert    (VBMP_FIRST_H + DS_HalfHorAndDownVert)

#define VBMP_N_DS_HalfVertAndRightHor   (VBMP_FIRST_N + DS_HalfVertAndRightHor)
#define VBMP_H_DS_HalfVertAndRightHor   (VBMP_FIRST_H + DS_HalfVertAndRightHor)

#define VBMP_N_DS_HalfHorAndUpVert      (VBMP_FIRST_N + DS_HalfHorAndUpVert)
#define VBMP_H_DS_HalfHorAndUpVert      (VBMP_FIRST_H + DS_HalfHorAndUpVert)

#define VBMP_N_DS_3Vert                 (VBMP_FIRST_N + DS_3Vert)
#define VBMP_H_DS_3Vert                 (VBMP_FIRST_H + DS_3Vert)

#define VBMP_N_DS_3Hor                  (VBMP_FIRST_N + DS_3Hor)
#define VBMP_H_DS_3Hor                  (VBMP_FIRST_H + DS_3Hor)

#define VBMP_N_DS_FullAndLeft3          (VBMP_FIRST_N + DS_FullAndLeft3)
#define VBMP_H_DS_FullAndLeft3          (VBMP_FIRST_H + DS_FullAndLeft3)

#define VBMP_N_DS_FullAndRight3         (VBMP_FIRST_N + DS_FullAndRight3)
#define VBMP_H_DS_FullAndRight3         (VBMP_FIRST_H + DS_FullAndRight3)

#endif

