#if !defined(_TV_DIALOG_INC_)
#define _TV_DIALOG_INC_

#include <windows.h>

#define  UCM_SYSABOUT  0x8880

#define  ID_BTN256_ABOUT     100

#define  ID_BTNBMP_FIRST_N    500
#define  ID_BTNBMP_FIRST_S    600
#define  ID_BTNBMP_FIRST_P    700

#define  DialogMainWindow   100
#define  DialogPalette      101


#define  ID_BTN_FIRST        100

#define  ID_BTN_VIEW        100
#define  ID_BTN_SAVE        103
#define  ID_BTN_PALETTE     112

#define  ID_BMP_VIEW        101
#define  ID_TXT_INFO        102
#define  ID_GRP_DIRECTORY   104
#define  ID_BMP_TRADEMARK   105

#define  ID_RADIO_QUANT     106
#define  ID_RADIO_MEDIUM    107
#define  ID_RADIO_LIGHT     108
#define  ID_RADIO_HAVY      109
#define  ID_CHECK_DIFFUSION 110
#define  ID_CHECK_NOISY         200
#define  ID_GRP_METHODS     111

#define  ID_RADIO_SYSPAL    112
#define  ID_RADIO_ADAPTPAL  113
#define  ID_EDIT_PALSIZE    114
#define  ID_GRP_PALSIZE     115


#define  ID_TRUEVIEW_ICON   106

#define  NUMB_BTNBMP 5

#define  ID_BTNBMP_LOAD_N     (ID_BTNBMP_FIRST_N + 1)
#define  ID_BTNBMP_LOAD_S     (ID_BTNBMP_FIRST_S + 1)
#define  ID_BTNBMP_LOAD_P     (ID_BTNBMP_FIRST_P + 1)

#define  ID_BTNBMP_SAVE_N     (ID_BTNBMP_FIRST_N + 2)
#define  ID_BTNBMP_SAVE_S     (ID_BTNBMP_FIRST_S + 2)
#define  ID_BTNBMP_SAVE_P     (ID_BTNBMP_FIRST_P + 2)

#define  ID_BTNBMP_VIEW_N     (ID_BTNBMP_FIRST_N + 3)
#define  ID_BTNBMP_VIEW_S     (ID_BTNBMP_FIRST_S + 3)
#define  ID_BTNBMP_VIEW_P     (ID_BTNBMP_FIRST_P + 3)

#define  ID_BTNBMP_EXIT_N     (ID_BTNBMP_FIRST_N + 4)
#define  ID_BTNBMP_EXIT_S     (ID_BTNBMP_FIRST_S + 4)
#define  ID_BTNBMP_EXIT_P     (ID_BTNBMP_FIRST_P + 4)

#define  ID_BTNBMP_PALETTE_N     (ID_BTNBMP_FIRST_N + 5)
#define  ID_BTNBMP_PALETTE_S     (ID_BTNBMP_FIRST_S + 5)
#define  ID_BTNBMP_PALETTE_P     (ID_BTNBMP_FIRST_P + 5)


#endif
