#if !defined(_ERRORS_INC_)
#define _ERRORS_INC_


#define ER_ICON_LOAD -7
#define ID_ICON_LOAD  100

#define ER_CREATE_BRUSH -8
#define ID_CREATE_BRUSH  106

#define ER_GET_DC  -9
#define ID_GET_DC  107

#define ER_FILEIO  -10
#define ID_FILEIO  108


#define ER_BITMAP_INVALID           -11
#define ID_BITMAP_INVALID           109
#define ER_BITMAP_NONWINDOWS        -12
#define ID_BITMAP_NONWINDOWS        110
#define ER_BITMAP_NOTSUPPORT_FORMAT -13
#define ID_BITMAP_NOTSUPPORT_FORMAT 111

#define ER_CREATEOBJECT      -14
#define ID_CREATEOBJECT      112

#define ID_INVALIDCLIENT     101
#define ID_INVALIDMAINWINDOW 102
#define ID_INVALIDMODULE     103
#define ID_INVALIDWINDOW     104
#define ID_OUTOFMEMORY       105

#define ER_BITMAPLOAD        -15
#define ID_BITMAPLOAD        113

#define ER_CURSORLOAD        -16
#define ID_CURSORLOAD        114

#define ER_CREATESURF        -17
#define ID_CREATESURF	     115


#endif

