#if !defined(_MY_CLASS_TYPES_)
#define _MY_CLASS_TYPES_

enum MyClassTypes { classtypeStatusWindow  = __firstUserClass + 1,
		    classtypeToolbarWindow = __firstUserClass + 2,
		    classtypeMDIChWindow   = __firstUserClass + 3,
		    classtypeToolbarButton = __firstUserClass + 4,
		    classtypeViewsDialog   = __firstUserClass + 5,
		    classtypeMDIFrame      = __firstUserClass + 6,
		    classtypeMediumItem    = __firstUserClass + 7,
		    classtypeCenterDlg     = __firstUserClass + 8,
		    classtypeValidator     = __firstUserClass + 9,
		    classtypeTConnector    = __firstUserClass + 10
                  };

#endif
