#if !defined(_WINDIV_TYP_)
#define _WINDIV_TYP_

/*
enum TDivStyle { DS_FullWin, DS_HalfVert, DS_HalfHor, DS_4, DS_HalfVertAndLeftHor,
		 DS_HalfHorAndDownVert, DS_HalfVertAndRightHor,
		 DS_HalfHorAndUpVert,
	         DS_3Vert, DS_3Hor, DS_FullAndLeft3, DS_FullAndRight3 };
  */
#define DS_FullWin               0
#define DS_HalfVert              1
#define DS_HalfHor               2 
#define DS_4                     3
#define DS_HalfVertAndLeftHor    4
#define DS_HalfHorAndDownVert    5
#define DS_HalfVertAndRightHor   6
#define DS_HalfHorAndUpVert      7
#define DS_3Vert                 8
#define DS_3Hor                  9
#define	DS_FullAndLeft3         10
#define	DS_FullAndRight3        11

#endif
